import "../Styles/Keyboard.css";
import { Key } from "./Key";
export const Keyboard = ({ pasar, OnPlay, Adivinado, Fallos, WinState }) => {
  const click = (e) => {
    return pasar(e);
  };
  return (
    <div className={OnPlay ? "container" : "container  nodisplay"}>
      <div className="Line">
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="q"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="w"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="e"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="r"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="t"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="y"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="u"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="i"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="o"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="p"
        />
      </div>
      <div className="Line">
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="a"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="s"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="d"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="f"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="g"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="h"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="j"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="k"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="l"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="ñ"
        />
      </div>
      <div className="Line">
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="Pista"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="z"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="x"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="c"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="v"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="b"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="n"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="m"
        />
        <Key
          click={click}
          Adivinado={Adivinado}
          Fallos={Fallos}
          WinState={WinState}
          letter="Reinicio"
        />
      </div>
    </div>
  );
};
